import { useState, useEffect } from 'react';
import UploadIcon from '../assets/upload-icon.svg';
import '../styles/VlogSection.css';

// Icon component for the cards
const VlogIcon = () => (
  <img src={UploadIcon} alt="Upload Icon" className="" />
);

// Main component
const VlogSection = () => {
  const totalCards = 6; // Total number of cards
  const [activeCardIndex, setActiveCardIndex] = useState(0);
  
  useEffect(() => {
    // Cycle through cards one by one
    const animationInterval = setInterval(() => {
      setActiveCardIndex(prev => (prev + 1) % totalCards);
    }, 3000);
    
    return () => clearInterval(animationInterval);
  }, []);

  return (
    <section className="vlog-section">
      <h1 className="vlog-heading">Create High-Fidelity Vlogs/Influencer Videos</h1>
      
      <p className="vlog-description">
        There have been some users creating super realistic vlogs and influencer videos with Veo 2. 
        The videos created have natural movements, such as eye blinks and lip-syncing, with minimal 
        noticeable flaws. And it can seamlessly transition between different environments.
      </p>
      
      <p className="vlog-subtitle">
        Here are the Veo 2 vlogs generated by the YouTube user Jerrod Lew:
      </p>
      
      <div className="slider-container">
        <div className="slider">
          {[...Array(totalCards)].map((_, index) => (
            <div 
              className={`slider-card ${activeCardIndex === index ? 'active' : ''}`}
              key={index}
              style={{
                transform: `translateX(${(index - activeCardIndex) * 110}%)`,
                zIndex: totalCards - Math.abs(activeCardIndex - index)
              }}
            >
              <VlogIcon />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default VlogSection;